<?php

/**
 * @file
 * Implementations of Commerce Hooks
 */


/**
 * Implements hook_commerce_kiala_settings_info().
 */
function commerce_kiala_ps_commerce_kiala_settings_info() {
  return array(
/*
    'packship_type' => array(
      'group' => 'packship',
      'default' => 'ws',
    ),
    'packship_ws_sender_id' => array(
      'group' => 'packship',
      'default' => '',
      'sensitive' => TRUE,
    ),
    'packship_ws_password' => array(
      'group' => 'packship',
      'default' => '',
      'sensitive' => TRUE,
      'password' => TRUE,
    ),
    'packship_ws_url' => array(
      'group' => 'packship',
      'default' => 'https://packandship-ws.kiala.com/psws/order',
    ),
    'packship_ws_params' => array(
      'group' => 'packship',
      'default' => array(
      ),
    ),
*/
  );
}
